# Инструмент, вешающий проверки на git-хук: перед каждым
# коммитом прогоняет линтеры по коммитируемым файлам.
# Если есть проблема - коммит не проходит.
# Смысл - ловить ошибки до отправки в CI

repos: # Корень, начинает список репозиториев со скриптами-проверками (хуками)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4 # Фиксируем версию ruff
    hooks: # Список конкретных проверок
      - id: ruff-check # Запуск линтера ruff (ошибки, синтаксис)
        args: [--fix] # Не только warning, но и автоисправление
      - id: ruff-format # Запуск форматтера (отступы, кавычки, длина строк)

  - repo: https://github.com/pre-commit/pre-commit-hooks # Стандартные проверки
    rev: v6.0.0
    hooks:
      #- id: trailing-whitespace # Удаляем невидимые пробелы в конце строк (не мусорим в истории git)
      #- id: end-of-file-fixer # Стандарт POSIX (файл заканчивается на 1 пустую строку)
      - id: check-yaml # Проверка всех .yaml/.yml на опечатки в синтаксисе
      - id: check-toml # Проверка всех .toml
      - id: check-added-large-files # Защищаем репозиторий от случайного добавления тяжелых файлов (умолч 500 КБ)
      - id: check-merge-conflict # Не забыли ли мы внутри файлов маркеры неразрешенных конфликтов
      - id: detect-private-key # Не забыл ли в коде приватные ключи

  - repo: local # Инструмент с локального устройства
    hooks:
      - id: mypy
        name: mypy # Имя отображения в терминале
        entry: uv run mypy # Команда запуска
        language: system # Говорит pre-commit, что uv и mypy уже установлены в ОС или вирт окружении и их не надо изолировать (запуск команды как есть)
        types: [python] # Запуск проверки только при изменении кода Python
        pass_filenames: false # По умолчанию проверка только измененных, а так читаем из pyproject.toml files = [backend] (проверяем все)
