services:
  postgres:
    image: postgres:17-alpine # Легкая версия, фиксируем конкретную
    container_name: kosta-postgres # Название контейнера
    env_file: config/.env # Официальный образ сам читает POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD (помнишь, как мы выносили в другом проекте)
    ports:
      - "5432:5432" # порт_на_хосте:порт_в_контейнере (Django будет работать на хосте и подключаться к базе как к localhost:5432)
    volumes:
    - pgdata:/var/lib/postgresql/data # Слева - именованный том Docker, справа - папка внутри контейнера с данными (без такой строки БД умрет вместе с контейнером)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"] # Проверяем, готов ли принимать соединения, $$ - используй наши переменные
      interval: 5s # Спрашивать каждые 5 секунд
      timeout: 3s # Время ожидания ответа
      retries: 5 # После 5 неудач пометить как unhealthy
      start_period: 10s # Неудачи в первые 10 секунд не считают провалами (пока поднимается контейнер)
    restart: unless-stopped # Поднимать, пока не остановлю вручную (даже после перезагрузки)

  redis:
    image: redis:7-alpine
    container_name: kosta-redis
    ports:
      - "6349:6349"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes: # Объявление именованных томов, иначе Docker не поймет, что за pgdata выше
  pgdata:
  redisdata:
