name: CI # Название workflow (в actions)

on: # Триггеры для автозапуска
  pull_request: # При создании/обновлении PR
  push: # При отправке изменений напрямую на сервер
    branches: [main] # Уточнение: только если в ветку main

concurrency: # Управление одновременными запусками тестов
  group: ci-${{ github.ref }} # Создаем уникальный id на PR/ветку (в фигурных скобках автоматически заменится на имя ветки)
  cancel-in-progress: true # Если запушил n раз подряд, прогоны (кроме последнего) отменяются - не тратим время на устаревший код

jobs: # Независимая единица работы (каждая с чистой своей виртуалкой)
  lint: # Название job. Проверка качества кода
    runs-on: ubuntu-latest # Показывает виртуальную машину, которая развернется
    timeout-minutes: 10 # Лимит по времени задачи. Если зависнет - github закроет, чтобы не тратить лимиты

    steps: # Шаг внутри job. Шаги делят одну файловую систему и идут по порядку
      - name: Забрать код # Название шага
        uses: actions/checkout@v4 # Готовый официальный плагин (Action), который скачивает код репозитория внутрь виртуальной машины

      - name: Поставить uv # Шаг - установка пакетного менеджера uv от Astral
        uses: astral-sh/setup-uv@v5 # Готовый официальный плагин
        with: # Блок передачи дополнительный настроек для плагина
          enable-cache: true # Кэширование зависимостей для более быстрого запуска последующих тестов
          cache-dependency-glob: uv.lock # Инструкция для кэша: обновлять кэш только в том случае, если изменился файл фиксации версий uv.lock

      - name: Поставить Python
        run: uv python install # Автоматически найти и установить Python

      - name: Поставить зависимости
        run: uv sync --locked # Синхронизирует виртуальное окружение с проектом. --locked требует ставить версии точно в соответствии с uv.lock

      - name: ruff check # Проверка качества кода линтером Ruff
        run: uv run ruff check . # Проверяем весь код на логические ошибки, неисп импорты, плохой стиль

      - name: ruff format # Проверка форматирования
        run: uv run ruff format --check . # Правильно ли расставлены пробелы, отступы, кавычки. --check - не исправлять, выдать ошибку

      - name: mypy # Шаг - статический анализ типов
        run: uv run mypy . # Проверка type hinting - правильно ли мы используем переменные